[package]
name = "sanic"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
bytes = "1.4.0"
clap = { version = "4.1.6", features = ["derive"] }
crc = "3.0.1"
thiserror = "1.0.38"
tracing = "0.1.37"
